workflows:
  ios-workflow:
    name: iOS Build (Sideload)
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get Flutter packages
        script: |
          cd mobile
          flutter packages get
      - name: Install pods
        script: |
          cd mobile/ios
          pod install
      - name: Build iOS App (No Signing)
        script: |
          cd mobile
          flutter build ios --release --no-codesign
      - name: Package .ipa
        script: |
          cd mobile/build/ios/iphoneos
          mkdir Payload
          cp -r Runner.app Payload
          zip -r Runner.ipa Payload
    artifacts:
      - mobile/build/ios/iphoneos/Runner.ipa


