// File generated by manual configuration (mimicking flutterfire config)
// Ignore issues as this is a manual fix
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions? get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        // Return null to let the plugin read from google-services.json
        return null;
      case TargetPlatform.iOS:
        // Return null to let the plugin read from GoogleService-Info.plist
        return null;
      case TargetPlatform.macOS:
        // Not configured
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAn1WrZmsT3uDV4N8zDQZ3DIFziCcBzRZg',
    appId: '1:504471880267:web:6a66aff5779318b60083ce',
    messagingSenderId: '504471880267',
    projectId: 'panta-3dc75',
    authDomain: 'panta-3dc75.firebaseapp.com',
    storageBucket: 'panta-3dc75.firebasestorage.app',
    measurementId: 'G-L7781ZV3N7',
  );
}
