#!/usr/bin/env bash
# fast_test.sh - Ultra-fast, targeted feedback loop runner for Panta
#
# Usage:
#   ./scripts/fast_test.sh                   # Runs both backend and aggregated mobile tests
#   ./scripts/fast_test.sh backend           # Runs Go tests in ~1-2s
#   ./scripts/fast_test.sh mobile            # Runs all Flutter tests via aggregated suite in ~35s
#   ./scripts/fast_test.sh mobile <pattern>  # Runs targeted Flutter test matching pattern in ~8-12s
#   ./scripts/fast_test.sh all               # Runs both backend and mobile tests

set -e

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BACKEND_DIR="$PROJECT_ROOT/backend"
MOBILE_DIR="$PROJECT_ROOT/mobile"
SUITE_TEST="$MOBILE_DIR/test/_suite_test.dart"

run_backend() {
    echo "⚡ [BACKEND] Running Go test suite..."
    start_time=$(date +%s)
    cd "$BACKEND_DIR"
    go test -v ./...
    end_time=$(date +%s)
    echo "✅ [BACKEND] All Go tests passed in $((end_time - start_time))s!"
}

generate_suite() {
    python3 -c "
import os

test_dir = '$MOBILE_DIR/test'
files = [f for f in os.listdir(test_dir) if f.endswith('_test.dart') and not f.startswith('_')]
files.sort()

imports = []
calls = []
for i, f in enumerate(files):
    prefix = f'test_{i}'
    imports.append(f\"import '{f}' as {prefix};\")
    calls.append(f\"  // {f}\n  {prefix}.main();\")

content = '''// Aggregated test suite generated by scripts/fast_test.sh
// Eliminates multi-process VM compilation overhead
import 'package:flutter_test/flutter_test.dart';

''' + '\n'.join(imports) + '''

void main() {
''' + '\n'.join(calls) + '''
}
'''

with open('$SUITE_TEST', 'w') as out:
    out.write(content)
"
}

run_mobile() {
    local target="$1"
    cd "$MOBILE_DIR"

    if [ -n "$target" ] && [ "$target" != "all" ]; then
        # Check if target is a file or search pattern
        local test_file=""
        if [ -f "$target" ]; then
            test_file="$target"
        elif [ -f "test/$target" ]; then
            test_file="test/$target"
        elif [ -f "test/${target}_test.dart" ]; then
            test_file="test/${target}_test.dart"
        else
            # Try finding matching file
            test_file=$(find test -name "*${target}*test.dart" | head -n 1)
        fi

        if [ -n "$test_file" ] && [ -f "$test_file" ]; then
            echo "⚡ [MOBILE] Running targeted test: $test_file..."
            start_time=$(date +%s)
            flutter test --no-test-assets "$test_file"
            end_time=$(date +%s)
            echo "✅ [MOBILE] Targeted test passed in $((end_time - start_time))s!"
            return 0
        else
            echo "⚠️ [MOBILE] No exact file found for '$target'. Running flutter test with pattern filter..."
            flutter test --plain-name "$target"
            return 0
        fi
    fi

    echo "⚡ [MOBILE] Running aggregated Flutter test suite (114+ tests)..."
    generate_suite
    start_time=$(date +%s)
    flutter test --no-test-assets test/_suite_test.dart
    end_time=$(date +%s)
    echo "✅ [MOBILE] Aggregated test suite passed in $((end_time - start_time))s!"
}

MODE="${1:-all}"
shift 2>/dev/null || true

case "$MODE" in
    backend)
        run_backend
        ;;
    mobile)
        run_mobile "$1"
        ;;
    all)
        overall_start=$(date +%s)
        run_backend
        echo ""
        run_mobile ""
        overall_end=$(date +%s)
        echo ""
        echo "🎉 [PANTA] Complete stack verification finished in $((overall_end - overall_start))s!"
        ;;
    *)
        # If passed an existing test name directly
        if [[ "$MODE" == *"test.dart"* ]] || [ -f "$MOBILE_DIR/test/$MODE" ]; then
            run_mobile "$MODE"
        else
            echo "Usage: $0 {backend|mobile [pattern]|all}"
            exit 1
        fi
        ;;
esac
